apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: private-quarkus-devfile-sample-faew
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ihmq-tenant/private-devfile/private-quarkus-devfile-sample-faew@sha256:3850d9281d4e9d3ee061b893f15ffe2832ae8c43fc9ec138d60e84b594e7ddaa
        name: my-java-quarkus
        resources: {}
status: {}
