apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-faew
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-faew
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-faew
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: private-quarkus-devfile-sample-faew
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: private-quarkus-devfile-sample-faew
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ihmq-tenant/private-devfile/private-quarkus-devfile-sample-faew@sha256:3850d9281d4e9d3ee061b893f15ffe2832ae8c43fc9ec138d60e84b594e7ddaa
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
